version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_transportes
      MYSQL_USER: andres
      MYSQL_PASSWORD: andres
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
