export const selfItemKey = [
  ['RAIDRA', 'idSelfItem'],
  ['RANMPR', 'name'],
  ['RANMDC', 'identityCard'],
  ['RAIDCA', 'idCatalog'],
  ['RAFEGN', 'dateGenerated'],
  ['RAHRGN', 'hourGenerated'],
  ['RAESGN', 'statusGenerated'],
  ['RAFECE', 'dateChangedGenerated'],
  ['RAHRCE', 'hourChangedGenerated'],
  ['RAESFN', 'statusFinal'],
  ['RANMPL', 'cardId'],
  ['RANMCH', 'vin'],
  ['RANMVH', 'vehicleNumber'],
  ['RAMOTI', 'reason'],
  ['RACORR', 'mail'],
  ['RAVTAR', 'value'],
  ['RAFECR', 'date'],
  ['RAUSCR', 'user'],
  ['RAFECA', 'dateChanged'],
  ['RAUSCA', 'userChanged'],
  ['PAGE', 'page'],
  ['ROWS', 'row'],
];

export const ItemDetailKey = [
  ['RDIDRD', 'idItemDetail'],
  ['RAIDRA', 'idSelfItem'],
  ['RDIDCA', 'idCatalog'],
  ['RDIDIC', 'idItemCatalog'],
  ['RDCDTR', 'itemCode'],
  ['RDDESL', 'nameItem'],
  ['RDVALO', 'ItemValue'],
  ['RDIDOP', 'orderPayment'],
  ['RDFEPG', 'datePayment'],
  ['RDHRPG', 'timePayment'],
  ['RDNMPG', 'namePayment'],
  ['RDIDPG', 'identityCardPayment'],
  ['RDESPG', 'statusPayment'],
  ['RDESTA', 'status'],
  ['RDFECR', 'date'],
  ['RDUSCR', 'user'],
  ['RDFECA', 'dateChanged'],
  ['RDUSCA', 'userChanged'],
  ['PAGE', 'page'],
  ['ROWS', 'row'],
];

export const DeleteItemKey = [
  ['EVIDEV', 'idDeleteItem'],
  ['RDIDRD', 'idItemDetail'],
  ['EVSECU', 'sequenceDoc'],
  ['EVANIO', 'year'],
  ['EVFECH', 'dateDelete'],
  ['EVCODC', 'documentCode'],
  ['EVAUX1', 'assistant1'],
  ['EVAUX2', 'assistant2'],
  ['EVFECR', 'date'],
  ['EVUSCR', 'user'],
  ['EVFECA', 'dateChanged'],
  ['EVUSCA', 'userChanged'],
  ['EVESTA', 'status'],
];
export const codeKey = [
  ['COIDCO', 'id'],
  ['INIDIN', 'idRegistration'],
  ['COCODI', 'code'],
  ['COFECR', 'dateCreated'],
  ['COMAIL', 'mail'],
  ['COESTA', 'status'],
];
export const itemKey = [
  ['TCTPIM', 'typeImport'],
  ['TCCDTR', 'code'],
  ['TCFCVG', 'validityDate'],
  ['TCVTAR', 'value'],
  ['TCZNCR', 'zone'],
  ['TCAGCR', 'agency'],
  ['TCUSCR', 'user'],
  ['TCFECR', 'createDate'],
  ['TCHOCR', 'createTime'],
  ['TCZNCA', 'changeZone'],
  ['TCAGCA', 'changeAgency'],
  ['TCUSCA', 'changeUser'],
  ['TCFECA', 'changeDate'],
  ['TCHOCA', 'changeTime'],
  ['TCTRAB', 'work'],
  ['TCPROG', 'changeWork'],
];
